// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgONcPzex6WE1NtOnQMxKofP4-5WSNFWk',
    appId: '1:1002671201023:web:eebe83ba30df2daa614aca',
    messagingSenderId: '1002671201023',
    projectId: 'healthtrack-9d144',
    authDomain: 'healthtrack-9d144.firebaseapp.com',
    storageBucket: 'healthtrack-9d144.firebasestorage.app',
    measurementId: 'G-370JW4H9FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ajYSzPDL5qhf5BHUvI_YCMPBZ1zzwWo',
    appId: '1:1002671201023:android:05ca5c0b931a08f9614aca',
    messagingSenderId: '1002671201023',
    projectId: 'healthtrack-9d144',
    storageBucket: 'healthtrack-9d144.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN_ZVjtk7t-x-O5oOpZcAnoctM0axA6k8',
    appId: '1:1002671201023:ios:ddbf4bf0a7a3a51c614aca',
    messagingSenderId: '1002671201023',
    projectId: 'healthtrack-9d144',
    storageBucket: 'healthtrack-9d144.firebasestorage.app',
    iosBundleId: 'com.example.healthtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN_ZVjtk7t-x-O5oOpZcAnoctM0axA6k8',
    appId: '1:1002671201023:ios:ddbf4bf0a7a3a51c614aca',
    messagingSenderId: '1002671201023',
    projectId: 'healthtrack-9d144',
    storageBucket: 'healthtrack-9d144.firebasestorage.app',
    iosBundleId: 'com.example.healthtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgONcPzex6WE1NtOnQMxKofP4-5WSNFWk',
    appId: '1:1002671201023:web:de1f46d226ff67c0614aca',
    messagingSenderId: '1002671201023',
    projectId: 'healthtrack-9d144',
    authDomain: 'healthtrack-9d144.firebaseapp.com',
    storageBucket: 'healthtrack-9d144.firebasestorage.app',
    measurementId: 'G-9MS0ZPP3XX',
  );
}
